version: '3.7'

services:
   bd:
      image: mariadb
      restart: always
      environment:
         MYSQL_USER: ${DB_USER}
         MYSQL_PASSWORD: ${DB_PASS}
         MYSQL_DATABASE: ${DB_NAME}
         MYSQL_ROOT_PASSWORD: ${DB_PASS}
      ports:
         - 3306:3306
      volumes:
         - ./data:/var/lib/mysql
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"                          

   app:
      image: app_segura2024
      volumes:
         - ./proyectoSegura:/code
         - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
         - bd
      environment:
         DJANGO_KEY: ${DJANGO_KEY}
         DB_NAME: ${DB_NAME}
         DB_USER: ${DB_USER}
         DB_PASS: ${DB_PASS}
         DB_HOST: bd
         DB_PORT: ${DB_PORT}  
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"                 

   nginx:
      image: nginx
      restart: always
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./proyectoSegura/proyectoSegura/static:/static
         - ./certificados:/certs
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"