version: '3.7'
services:
   tareas:
      image: tareas_segura2024
      build: .
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"                 
